<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0">
<context>
    <name>_s_MainContainer</name>
    <message>
        <location filename="main_container.py" line="443"/>
        <source>Incorrect File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="443"/>
        <source>The image couldn&apos;t be open</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="463"/>
        <source>Open File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="530"/>
        <source> (Read-Only)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="547"/>
        <source>The file couldn&apos;t be open</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="621"/>
        <source>Close Deleted File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="621"/>
        <source>Are you sure you want to close the deleted file?
The content will be completely deleted.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="696"/>
        <source>File Saved: %s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="710"/>
        <source>Save Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="710"/>
        <source>The file couldn&apos;t be saved!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="676"/>
        <source>Save File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="704"/>
        <source>File Already Exists</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="704"/>
        <source>Invalid Path: the file &apos;%s&apos; already exists.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="712"/>
        <source>New Document</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main_container.py" line="792"/>
        <source>Python Documentation</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
